NUMBER_COLUMNS = 7
NUMBER_LINES = 6


NUMBER_PLAYERS = 2
PLAYER_ONE = 0
PLAYER_TWO = 1
COLOR_PLAYER_ONE = '🔵'
COLOR_PLAYER_TWO= '🔴'


TURN_TIME = 5
VICTORY_NUMBER = 4
STORAGE_PATH= 'storage_manager/game_history.json'
EXIT_KEY='esc'
